# Generated by Django 3.2.7 on 2021-09-08 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_car_garage', '0002_vehicle_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='completed',
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('currentOdometer', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='my_car_garage.vehicle')),
            ],
        ),
    ]
