# Generated by Django 3.2.7 on 2021-09-08 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_car_garage', '0003_auto_20210908_0025'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
    ]
