# Generated by Django 3.2.7 on 2021-09-08 00:30

from django.db import migrations

def seed(apps, schema_editor):
    User = apps.get_model('my_car_garage', 'User')
    Vehicle = apps.get_model('my_car_garage', 'Vehicle')
    Note = apps.get_model('my_car_garage', 'Note')
    
    andrew = User(name = "Andrew", location = "Northern California")
    andrew.save()
    honda = Vehicle(user = andrew, make="Honda")
    honda.save()
    Note(vehicle = honda, service= "oil change", currentOdometer= 9999)
    
    
def fallow(apps, schema_editor):
    User = apps.get_model('my_car_garage', 'User')
    Vehicle = apps.get_model('my_car_garage', 'Vehicle')
    User.objects.all().delete()
    Vehicle.objects.all().delete()
    
    

class Migration(migrations.Migration):

    dependencies = [
        ('my_car_garage', '0004_rename_notes_note'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
