# Generated by Django 3.2.7 on 2021-09-08 01:18

from django.db import migrations

def seed(apps, schema_editor):
    User = apps.get_model('my_car_garage', 'User')
    Vehicle = apps.get_model('my_car_garage', 'Vehicle')
    Note = apps.get_model('my_car_garage', 'Note')
    
    andrew = User(name = "Andrew", location = "Northern California")
    andrew.save()
    # honda = Vehicle(user = "Andrew", make="Honda")
    # honda.save()
    # Note(vehicle = honda, service= "oil change", current_Odometer= 9999).save()
    
    
def fallow(apps, schema_editor):
    User = apps.get_model('my_car_garage', 'User')
    Vehicle = apps.get_model('my_car_garage', 'Vehicle')
    User.objects.all().delete()
    Vehicle.objects.all().delete()
    

class Migration(migrations.Migration):

    dependencies = [
        ('my_car_garage', '0005_auto_20210908_0030'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
