# Generated by Django 3.2.7 on 2021-09-08 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_car_garage', '0006_auto_20210908_0118'),
    ]

    operations = [
    ]
