# Generated by Django 3.2.7 on 2021-09-08 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_car_garage', '0008_auto_20210908_0259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='currentOdometer',
            new_name='current_odometer',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='my_car_garage.user'),
        ),
    ]
