# Generated by Django 3.2.7 on 2021-09-12 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_car_garage', '0010_alter_vehicle_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='my_car_garage.vehicle'),
        ),
    ]
